"""Completeness report: who spoke, who did not, and which texts are missing."""

from collections import Counter

from .config import REPORTS_DIR, session_year
from .model import Speech
from .render import ordinal, language_name


def _table(header: list[str], rows: list[list]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def write_completeness_report(session: int, speeches: list[Speech], pending: list[str], delegations: list[dict]) -> None:
    spoke = {s.slug for s in speeches}
    members = [d for d in delegations if d["status"] == "member_state"]
    member_speeches = [s for s in speeches if s.status == "member_state"]
    silent = [d for d in members if d["slug"] not in spoke and d["slug"] not in pending]
    others = [s for s in speeches if s.status != "member_state"]
    not_represented = [d for d in delegations if d["status"] == "not_represented"]
    unknown = [s for s in speeches if s.status == "unknown"]

    has_original_statement = sum(any(v.role == "original" and v.kind == "statement" and v.text for v in s.texts) for s in speeches)
    has_original_any = sum(any(v.role == "original" and v.text for v in s.texts) for s in speeches)
    english = Counter(s.english_source for s in speeches)
    unknown_language = sum(s.original_language is None for s in speeches)
    roles = Counter(s.role_group for s in member_speeches)
    languages = Counter(s.original_language for s in speeches)

    out = [
        f"# Completeness: {ordinal(session)} session ({session_year(session)})\n",
        f"{len(member_speeches)} of {len(members)} member states have a published speech, and {len(pending)} listed pages are not yet published. "
        f"{has_original_any} of {len(speeches)} speeches have original-language text, and {len(speeches) - english['none']} have English text.\n",
        "Generated by `make session`; do not edit by hand.\n",
        "## Delegations\n",
        _table(["Group", "Count"], [
            ["Member states with a published speech", len(member_speeches)],
            ["Listed on the site but not yet published", len(pending)],
            ["Member states with no speech", len(silent)],
            ["Observers, the EU and UN officials who spoke", len(others)],
            ["Not represented at the UN", len(not_represented)],
        ]),
    ]
    if silent:
        out += ["**Member states with no speech:** " + ", ".join(d["name"] for d in silent) + "\n"]
    if pending:
        out += ["**Listed but not yet published:** " + ", ".join(sorted(pending)) + "\n"]
    if not_represented:
        out += ["**Not represented:** " + ", ".join(d["name"] for d in not_represented) + ". It has no seat, so it gives no general debate speech. This is not a gap in the data.\n"]
    if unknown:
        out += ["**On the site but missing from `data/reference/delegations.csv`:** " + ", ".join(s.slug for s in unknown) + "\n"]

    out += ["## Who spoke for member states\n", _table(["Rank of speaker", "Speeches"], [[k, v] for k, v in roles.most_common()])]
    out += ["## Texts\n", _table(["Measure", "Speeches"], [
        ["Original language from the official statement pdf", has_original_statement],
        ["Original language from the AI transcript only", has_original_any - has_original_statement],
        ["No original-language text", len(speeches) - has_original_any - unknown_language],
        ["Spoken language not known", unknown_language],
        ["English: the speech was in English", english["original"]],
        ["English: translation filed by the delegation", english["delegation_translation"]],
        ["English: filed by the delegation, spoken language not known", english["delegation_english_text"]],
        ["English: AI transcript of the UN interpretation", english["un_interpretation_transcript"]],
        ["English: none", english["none"]],
    ])]
    out += ["## Original languages\n", _table(["Language", "Speeches"], [[language_name(k), v] for k, v in languages.most_common()])]

    gaps = [[f"[{s.delegation}](../data/speeches/{session}/{s.slug}/README.md)", g] for s in sorted(speeches, key=lambda s: s.slug) for g in s.gaps]
    out += ["## Gaps to close by hand\n", _table(["Speech", "Gap"], gaps) if gaps else "None.\n"]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (REPORTS_DIR / f"completeness_{session}.md").write_text("\n".join(out), encoding="utf-8")
